name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build custom Tegola image
      run: docker build . --file Dockerfile.tegola --tag docker.pkg.github.com/xor22h/vector-map/tegola:$(date +%s)
